on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOARCH: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: macOS build
        uses: shoukoo/golang-pipeline/go1.13/release@master
        #if: github.event.action == 'published'
        env:
          GOOS: darwin
      - name: Windows build
        uses: shoukoo/golang-pipeline/go1.13/release@master
        #if: github.event.action == 'published'
        env:
          GOOS: windows
      - name: Linux build
        uses: shoukoo/golang-pipeline/go1.13/release@master
        #if: github.event.action == 'published'
        env:
          GOOS: linux

